// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetDocumentsData, GetDocumentsErrors, GetDocumentsResponses, GetOwnersData, GetOwnersErrors, GetOwnersResponses, GetScheduledData, GetScheduledErrors, GetScheduledResponses, PostTransferAllData, PostTransferAllErrors, PostTransferAllResponses, PostTransferData, PostTransferErrors, PostTransferResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getDocuments = <ThrowOnError extends boolean = false>(options?: Options<GetDocumentsData, ThrowOnError>): RequestResult<GetDocumentsResponses, GetDocumentsErrors, ThrowOnError> => (options?.client ?? client).get<GetDocumentsResponses, GetDocumentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/contentdashboard/api/v1/documents',
    ...options
});

export const getOwners = <ThrowOnError extends boolean = false>(options?: Options<GetOwnersData, ThrowOnError>): RequestResult<GetOwnersResponses, GetOwnersErrors, ThrowOnError> => (options?.client ?? client).get<GetOwnersResponses, GetOwnersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/contentdashboard/api/v1/owners',
    ...options
});

export const getScheduled = <ThrowOnError extends boolean = false>(options?: Options<GetScheduledData, ThrowOnError>): RequestResult<GetScheduledResponses, GetScheduledErrors, ThrowOnError> => (options?.client ?? client).get<GetScheduledResponses, GetScheduledErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/contentdashboard/api/v1/scheduled',
    ...options
});

export const postTransfer = <ThrowOnError extends boolean = false>(options?: Options<PostTransferData, ThrowOnError>): RequestResult<PostTransferResponses, PostTransferErrors, ThrowOnError> => (options?.client ?? client).post<PostTransferResponses, PostTransferErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/contentdashboard/api/v1/transfer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postTransferAll = <ThrowOnError extends boolean = false>(options?: Options<PostTransferAllData, ThrowOnError>): RequestResult<PostTransferAllResponses, PostTransferAllErrors, ThrowOnError> => (options?.client ?? client).post<PostTransferAllResponses, PostTransferAllErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/contentdashboard/api/v1/transfer-all',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
