// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44366/' | (string & {});
};

export type ContentOwnerResponseModel = {
    id: string;
    name: string;
    email?: null | string;
    documentCount: number;
};

export type DocumentOwnerModel = {
    id?: null | string;
    name: string;
};

export type OwnedDocumentResponseModel = {
    id: string;
    name: string;
    contentTypeAlias: string;
    icon?: null | string;
    published: boolean;
    edited: boolean;
    updateDate: string;
    createDate: string;
    owner?: null | DocumentOwnerModel;
};

export type OwnedDocumentSortField = 'Name' | 'UpdateDate';

export type PagedOwnedDocumentResponseModel = {
    total: number;
    items: Array<OwnedDocumentResponseModel>;
};

export type PagedScheduledDocumentResponseModel = {
    total: number;
    items: Array<ScheduledDocumentResponseModel>;
};

export type ScheduleAction = 'Publish' | 'Unpublish';

export type ScheduledDocumentResponseModel = {
    id: string;
    name: string;
    action: ScheduleAction;
    date: string;
    culture?: null | string;
    owner?: null | DocumentOwnerModel;
};

export type SortDirection = 'Ascending' | 'Descending';

export type TransferAllOwnershipRequestModel = {
    fromUserId: string;
    toUserId: string;
};

export type TransferOwnershipRequestModel = {
    documentIds: Array<string>;
    newOwnerId: string;
};

export type TransferOwnershipResponseModel = {
    affectedCount: number;
};

export type GetDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        ownerId?: string;
        skip?: number;
        take?: number;
        orderBy?: OwnedDocumentSortField;
        direction?: SortDirection;
    };
    url: '/umbraco/contentdashboard/api/v1/documents';
};

export type GetDocumentsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDocumentsResponses = {
    /**
     * OK
     */
    200: PagedOwnedDocumentResponseModel;
};

export type GetDocumentsResponse = GetDocumentsResponses[keyof GetDocumentsResponses];

export type GetOwnersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/contentdashboard/api/v1/owners';
};

export type GetOwnersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetOwnersResponses = {
    /**
     * OK
     */
    200: Array<ContentOwnerResponseModel>;
};

export type GetOwnersResponse = GetOwnersResponses[keyof GetOwnersResponses];

export type GetScheduledData = {
    body?: never;
    path?: never;
    query?: {
        ownerId?: string;
        allOwners?: boolean;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/contentdashboard/api/v1/scheduled';
};

export type GetScheduledErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetScheduledResponses = {
    /**
     * OK
     */
    200: PagedScheduledDocumentResponseModel;
};

export type GetScheduledResponse = GetScheduledResponses[keyof GetScheduledResponses];

export type PostTransferData = {
    body: TransferOwnershipRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/contentdashboard/api/v1/transfer';
};

export type PostTransferErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostTransferResponses = {
    /**
     * OK
     */
    200: TransferOwnershipResponseModel;
};

export type PostTransferResponse = PostTransferResponses[keyof PostTransferResponses];

export type PostTransferAllData = {
    body: TransferAllOwnershipRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/contentdashboard/api/v1/transfer-all';
};

export type PostTransferAllErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PostTransferAllResponses = {
    /**
     * OK
     */
    200: TransferOwnershipResponseModel;
};

export type PostTransferAllResponse = PostTransferAllResponses[keyof PostTransferAllResponses];
